# Generated by Django 5.2.1 on 2025-05-22 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('juda_ham_qoniqaman', models.IntegerField(default=0)),
                ('asosan_qoniqaman', models.IntegerField(default=0)),
                ('ortacha_qoniqaman', models.IntegerField(default=0)),
                ('qoniqmayman', models.IntegerField(default=0)),
                ('umuman_qoniqaman', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.teacherusersstats')),
            ],
        ),
    ]
