# Generated by Django 5.2.1 on 2025-05-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teacherquestionresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherQuestionResponse',
        ),
    ]
